# This Cloud Build configuration deploys a Node.js application to Cloud Run.
# It builds the application, then deploys it while injecting secrets
# from Google Secret Manager as environment variables.

steps:
# Step 1: Install Node.js dependencies
# This uses the 'npm' builder.
- name: 'gcr.io/cloud-builders/npm'
  id: Install Dependencies
  args: ['install']

# Step 2: Build the frontend application (if applicable, otherwise remove if this is a backend-only service)
# Assuming your package.json has a 'build' script.
- name: 'gcr.io/cloud-builders/npm'
  id: Build Frontend
  args: ['run', 'build'] # Adjust 'build' if your script name is different

# Step 3: Build the Docker image
# This uses the 'cloud-sdk' builder and Docker to build your container image.
# The Dockerfile must be in the current directory (which is freight-file-tracker).
- name: 'gcr.io/cloud-builders/docker'
  id: Build Docker Image
  args: ['build', '-t', "gcr.io/$PROJECT_ID/freight-email-service:$COMMIT_SHA", '.']

# Step 4: Deploy to Cloud Run
# This step deploys the built Docker image to Cloud Run.
# It uses the secrets from Secret Manager as environment variables for the Cloud Run service.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy to Cloud Run
  entrypoint: bash # Changed entrypoint to bash
  args:
    - '-c' # This tells bash to execute the following string as a command
    - | # Multi-line string for the gcloud command
      gcloud run deploy freight-email-service \
        --image="gcr.io/$PROJECT_ID/freight-email-service:$COMMIT_SHA" \
        --region=us-central1 \
        --allow-unauthenticated \
        --platform=managed \
        --set-env-vars=FIREBASE_SERVICE_ACCOUNT_KEY="$$SECRET_FIREBASE_SERVICE_ACCOUNT_KEY_SECRET",GMAIL_CLIENT_ID="$$SECRET_GMAIL_CLIENT_ID_SECRET",GMAIL_CLIENT_SECRET="$$SECRET_GMAIL_CLIENT_SECRET_SECRET",GMAIL_REFRESH_TOKEN="$$SECRET_GMAIL_REFRESH_TOKEN_SECRET",GMAIL_REDIRECT_URL="$$SECRET_GMAIL_REDIRECT_URL_SECRET" \
        --update-secrets=FIREBASE_SERVICE_ACCOUNT_KEY_SECRET=firebase-service-account-key:latest,GMAIL_CLIENT_ID_SECRET=gmail-client-id:latest,GMAIL_CLIENT_SECRET_SECRET=gmail-client-secret:latest,GMAIL_REFRESH_TOKEN_SECRET=gmail-refresh-token:latest,GMAIL_REDIRECT_URL_SECRET=gmail-redirect-url:latest

# This section tells Cloud Build to send logs directly to Cloud Logging.
options:
  logging: CLOUD_LOGGING_ONLY

# List of secrets to be accessed by Cloud Build during the build process
# IMPORTANT: The 'env' names here MUST start with 'SECRET_'
availableSecrets:
  secretManager:
  - versionName: projects/596797154216/secrets/firebase-service-account-key/versions/latest
    env: 'SECRET_FIREBASE_SERVICE_ACCOUNT_KEY_SECRET'
  - versionName: projects/596797154216/secrets/gmail-client-id/versions/latest
    env: 'SECRET_GMAIL_CLIENT_ID_SECRET'
  - versionName: projects/596797154216/secrets/gmail-client-secret/versions/latest
    env: 'SECRET_GMAIL_CLIENT_SECRET_SECRET'
  - versionName: projects/596797154216/secrets/gmail-refresh-token/versions/latest
    env: 'SECRET_GMAIL_REFRESH_TOKEN_SECRET'
  - versionName: projects/596797154216/secrets/gmail-redirect-url/versions/latest
    env: 'SECRET_GMAIL_REDIRECT_URL_SECRET'
